<?php
/**
 * Default settings for the fkstaskrepo plugin
 *
 * @author Michal Koutný <michal@fykos.cz>
 */

// Admin part - XML import and page burning
    // Template of pages with tasks generated by XML import
        $conf['series_template'] = 'system:series_template';
    // ID of new pages with tasks generated by XML import
        $conf['page_path_mask_cs'] = 'rocnik%1$02d:ulohy:serie%2$d';
        $conf['page_path_mask_en'] = 'year%1$02d:tasks:series%2$d';

// Web part - tasks
    $conf['brochure_path_cs']='rocnik%1$02d:ulohy:pdf:%2$d:brozurka_%1$02d_%2$d.pdf';
    $conf['brochure_path_en']='year%1$02d:tasks:pdf:%2$d:brochure_%1$02d_%2$d.pdf';

    $conf['solution_path_cs']='rocnik%1$02d:ulohy:pdf:%2$d:priklad_%1$02d_%2$d_%3$s.pdf';
    $conf['solution_path_en']='year%1$02d:tasks:pdf:%2$d:task_%1$02d_%2$d_%3$s.pdf';

    $conf['yearbook_path_cs']='rocnik%1$02d:ulohy:pdf:rocenka%1$02d.pdf';
    $conf['serial_path_cs']='rocnik%1$02d:ulohy:pdf:serial%1$02d_%2$d.pdf';

    $conf['archive_path_cs']='ulohy:start';
    $conf['archive_path_en']='tasks:start';

    // Preffered place to save figures and other files
        $conf['attachment_path_cs'] = 'rocnik%1$02d:ulohy:prilohy:%2$d:%3$s';
        $conf['attachment_path_en'] = 'year%1$02d:tasks:attachments:%2$d:%3$s';

// Meta ID of current task
    $conf['task_data_meta_path'] = 'tasks:%1$d:%2$d:%3$s.json';

// Webserver paths
    $conf['remote_path_mask'] = '/fykos%1$s/batch%2$s/out/zadaniWeb%2$s-new.xml';
    $conf['remote_brochure_path_mask'] = '/fykos%1$d/batch%2$d/out/serie%2$d.pdf';
    $conf['remote_serial_path_mask'] = '/fykos%1$d/batch%2$d/out/serial%2$d.pdf';
    $conf['remote_task_solution_path_mask'] = '/fykos%1$d/batch%2$d/out/reseni%2$d-%5$s.pdf';

// List of tasks labels and numbers used in the contest
    $conf['label_number_tasks_used'] = '1/1,2/2,3/3,4/4,5/5,P/6,E/7,S/8';

// List of languages, first is default
    $conf['languages_used'] = 'cs,en';
